 # Guatemala 19 de julio del 2016
 # Datum, Taller Cassandra
 # Tarea 1, Caso 1
 # Configuracion maquina virtual, para instalar prerrequisitos oracle 12c R1
 # Keneth Efrén Ubeda Arriaza
 # fuente: https://oracle-base.com/articles/12c/oracle-db-12cr1-installation-on-oracle-linux-6
 # Sistema operativo Oracle linux 6

Vagrant.configure("2") do |config|

  config.vm.box = "OracleLinux"

   config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
     vb.cpus = "2"
   end

   config.vm.provision "shell", inline: <<-SHELL
     yum list
     yum install -y puppet
     puppet module install puppetlabs-stdlib
     puppet module install puppetlabs-reboot
   SHELL

   config.vm.provision :puppet do |puppet|
        puppet.manifests_path = 'puppet/manifests'
        puppet.manifest_file  = 'config.pp'
        puppet.options        = '--verbose'
   end

   config.vm.provision :reload

end
