 # Guatemala 19 de julio del 2016
 # Datum, Taller Cassandra
 # Tarea 1, Caso 2
 # 3 nodos de Cassandra
 # Keneth Efrén Ubeda Arriaza
 # Sistema operativo CentOs 7

Vagrant.configure("2") do |config|

 # --------------------------- NODO 1 -----------------------------------

  config.vm.define 'nodo1' do |nodo1|
    nodo1.vm.box = "CentOs"

    # Setup netowrking and port forwarding
    nodo1.vm.hostname = "cas00.datum.com.gt"
    nodo1.vm.network 'private_network', ip: '5.5.5.0'
    nodo1.vm.network 'forwarded_port', guest: 9042, host: 9004

    nodo1.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
     vb.cpus = "1"
   end

  config.vm.provision "shell", inline: <<-SHELL
     puppet module install puppetlabs-stdlib
   SHELL

    nodo1.vm.provision :puppet do |puppet|
      puppet.manifests_path = 'puppet/manifests'
      puppet.manifest_file  = 'puppet.pp'
      puppet.options        = '--verbose'
   end
  end
 # --------------------------- NODO 2 -----------------------------------

  config.vm.define 'nodo2' do |nodo2|
    nodo2.vm.box = "CentOs"

    # Setup netowrking and port forwarding
    nodo2.vm.hostname = "cas00.datum.com.gt"
    nodo2.vm.network 'private_network', ip: '5.5.5.1'
    nodo2.vm.network 'forwarded_port', guest: 9042, host: 9005

    nodo2.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
     vb.cpus = "1"
   end

  config.vm.provision "shell", inline: <<-SHELL
     puppet module install puppetlabs-stdlib
   SHELL

    nodo2.vm.provision :puppet do |puppet|
      puppet.manifests_path = 'puppet/manifests'
      puppet.manifest_file  = 'puppet1.pp'
      puppet.options        = '--verbose'
   end
  end
 # --------------------------- NODO 3 -----------------------------------

  config.vm.define 'nodo3' do |nodo3|
    nodo3.vm.box = "CentOs"

    # Setup netowrking and port forwarding
    nodo3.vm.hostname = "cas00.datum.com.gt"
    nodo3.vm.network 'private_network', ip: '5.5.5.2'
    nodo3.vm.network 'forwarded_port', guest: 9042, host: 9006

    nodo3.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
     vb.cpus = "1"
   end

  config.vm.provision "shell", inline: <<-SHELL
     puppet module install puppetlabs-stdlib
   SHELL

    nodo3.vm.provision :puppet do |puppet|
      puppet.manifests_path = 'puppet/manifests'
      puppet.manifest_file  = 'puppet2.pp'
      puppet.options        = '--verbose'
   end
  end
end
